// Per-namespace presentation hints for the translation editor
// (`src/app/(cms)/admin/messages`). Purely additive: namespaces or keys not
// listed here keep the default behavior (alphabetical order, key as label).

export type FieldKind = "text" | "rich";

export type FieldSchema = {
  /** Human-readable label shown instead of the raw key. */
  label?: string;
  /** "rich" renders a larger textarea with a tag-support caption. */
  kind?: FieldKind;
};

export type NamespaceSchema = {
  /** Explicit display order; any keys not listed are appended alphabetically. */
  order?: string[];
  fields?: Record<string, FieldSchema>;
};

/**
 * Namespaces to merge into a single CMS section.
 * Key = display name shown in the editor; value = member namespaces in display order.
 */
export const NAMESPACE_GROUPS: Record<string, string[]> = {
  Home: ["Hero", "Home"],
};

export const NAMESPACE_SCHEMAS: Record<string, NamespaceSchema> = {
  Hero: {
    order: [
      "slide1Label", "slide1Title", "slide1Subtitle",
      "slide2Label", "slide2Title", "slide2Subtitle",
      "slide3Label", "slide3Title", "slide3Subtitle",
      "slide4Label", "slide4Title", "slide4Subtitle",
      "exploreSolutions", "talkToTeam", "slideAria",
    ],
    fields: {
      slide1Label: { label: "Slide 1 — Label" },
      slide1Title: { label: "Slide 1 — Judul" },
      slide1Subtitle: { label: "Slide 1 — Subtitle" },
      slide2Label: { label: "Slide 2 — Label" },
      slide2Title: { label: "Slide 2 — Judul" },
      slide2Subtitle: { label: "Slide 2 — Subtitle" },
      slide3Label: { label: "Slide 3 — Label" },
      slide3Title: { label: "Slide 3 — Judul" },
      slide3Subtitle: { label: "Slide 3 — Subtitle" },
      slide4Label: { label: "Slide 4 — Label" },
      slide4Title: { label: "Slide 4 — Judul" },
      slide4Subtitle: { label: "Slide 4 — Subtitle" },
      exploreSolutions: { label: "Tombol (Explore Solutions)" },
      talkToTeam: { label: "Tombol (Talk to Team)" },
      slideAria: { label: "Aria Label (Slide)" },
    },
  },
  Home: {
    order: [
      "tagline", "description",
      "stat1Value", "stat1Label",
      "stat2Value", "stat2Label",
      "stat3Value", "stat3Label",
      "stat4Value", "stat4Label",
      "exploreSolutions", "solutionsHeading", "solutionsBody", "exploreSolution",
      "solution1Title", "solution1Description",
      "solution2Title", "solution2Description",
      "solution3Title", "solution3Description",
      "solution4Title", "solution4Description",
      "dataCenterEyebrow", "dataCenterHeading", "dataCenterBody", "dataCenterCta",
      "whyEyebrow", "whyHeading",
      "why1Title", "why1Description",
      "why2Title", "why2Description",
      "why3Title", "why3Description",
      "why4Title", "why4Description",
      "trustedBy",
      "closingHeading", "closingBody", "closingCta",
      "contactHeading", "contactBody",
    ],
    fields: {
      tagline: { label: "Heading 2 (Tagline)", kind: "rich" },
      description: { label: "Deskripsi (Tagline)" },
      stat1Value: { label: "Stat 1 — Nilai" },
      stat1Label: { label: "Stat 1 — Label" },
      stat2Value: { label: "Stat 2 — Nilai" },
      stat2Label: { label: "Stat 2 — Label" },
      stat3Value: { label: "Stat 3 — Nilai" },
      stat3Label: { label: "Stat 3 — Label" },
      stat4Value: { label: "Stat 4 — Nilai" },
      stat4Label: { label: "Stat 4 — Label" },
      exploreSolutions: { label: "Heading 2 (Explore Solution)" },
      solutionsHeading: { label: "Span Label (Explore Solution)" },
      solutionsBody: { label: "Deskripsi (Explore Solution)" },
      exploreSolution: { label: "Tombol (Explore Solution)" },
      solution1Title: { label: "Solusi 1 — Judul" },
      solution1Description: { label: "Solusi 1 — Deskripsi" },
      solution2Title: { label: "Solusi 2 — Judul" },
      solution2Description: { label: "Solusi 2 — Deskripsi" },
      solution3Title: { label: "Solusi 3 — Judul" },
      solution3Description: { label: "Solusi 3 — Deskripsi" },
      solution4Title: { label: "Solusi 4 — Judul" },
      solution4Description: { label: "Solusi 4 — Deskripsi" },
      dataCenterEyebrow: { label: "Heading 2 (Data Center)" },
      dataCenterHeading: { label: "Span Label (Data Center)" },
      dataCenterBody: { label: "Deskripsi (Data Center)" },
      dataCenterCta: { label: "Tombol CTA (Data Center)" },
      whyEyebrow: { label: "Heading 2 (Why SUME)" },
      whyHeading: { label: "Span Label (Why SUME)" },
      why1Title: { label: "Why 1 — Judul" },
      why1Description: { label: "Why 1 — Deskripsi" },
      why2Title: { label: "Why 2 — Judul" },
      why2Description: { label: "Why 2 — Deskripsi" },
      why3Title: { label: "Why 3 — Judul" },
      why3Description: { label: "Why 3 — Deskripsi" },
      why4Title: { label: "Why 4 — Judul" },
      why4Description: { label: "Why 4 — Deskripsi" },
      trustedBy: { label: "Heading 2 (Trusted By)" },
      closingHeading: { label: "Judul (Closing CTA)" },
      closingBody: { label: "Deskripsi (Closing CTA)" },
      closingCta: { label: "Tombol (Closing CTA)" },
      contactHeading: { label: "Judul (Contact)" },
      contactBody: { label: "Deskripsi (Contact)" },
    },
  },
  AboutPage: {
    order: [
      "metaTitle",
      "metaDescription",
      "headerEyebrow",
      "headerTitle",
      "headerDescription",
      "whoWeAreEyebrow",
      "whoWeAreHeading",
      "whoWeAreBody",
      "journeyEyebrow",
      "journeyHeading",
      "journeyNote",
      "milestone1Event",
      "milestone2Event",
      "milestone3Event",
      "milestone4Event",
      "milestone5Event",
      "milestone6Event",
      "apartEyebrow",
      "apartHeading",
      "apart1Title",
      "apart1Body",
      "apart2Title",
      "apart2Body",
      "apart3Title",
      "apart3Body",
      "apart4Title",
      "apart4Body",
      "certsEyebrow",
      "certsHeading",
      "certsBody",
      "cert1Name",
      "cert1Detail",
      "cert2Name",
      "cert2Detail",
      "cert3Name",
      "cert3Detail",
      "cert4Name",
      "cert4Detail",
      "ctaTitle",
      "ctaBody",
      "ctaButton",
    ],
    fields: {
      metaTitle: { label: "Meta Title" },
      metaDescription: { label: "Meta Description" },
      headerEyebrow: { label: "Heading 1" },
      headerTitle: { label: "Span Label" },
      headerDescription: { label: "Deskripsi Header" },
      whoWeAreEyebrow: { label: "Heading 2 (Siapa Kami)" },
      whoWeAreHeading: { label: "Span Label (Siapa Kami)" },
      whoWeAreBody: { label: "Deskripsi (Siapa Kami)", kind: "rich" },
      journeyEyebrow: { label: "Heading 2 (Perjalanan Kami)" },
      journeyHeading: { label: "Span Label (Perjalanan Kami)" },
      journeyNote: { label: "Catatan (Perjalanan Kami)" },
      milestone1Event: { label: "Tonggak 1 — Peristiwa (2014)" },
      milestone2Event: { label: "Tonggak 2 — Peristiwa (2015)" },
      milestone3Event: { label: "Tonggak 3 — Peristiwa (2017)" },
      milestone4Event: { label: "Tonggak 4 — Peristiwa (2025)" },
      milestone5Event: { label: "Tonggak 5 — Peristiwa (2025)" },
      milestone6Event: { label: "Tonggak 6 — Peristiwa (2026)" },
      apartEyebrow: { label: "Heading 2 (Yang Membedakan Kami)" },
      apartHeading: { label: "Span Label (Yang Membedakan Kami)" },
      apart1Title: { label: "Kartu 1 — Judul" },
      apart1Body: { label: "Kartu 1 — Deskripsi" },
      apart2Title: { label: "Kartu 2 — Judul" },
      apart2Body: { label: "Kartu 2 — Deskripsi" },
      apart3Title: { label: "Kartu 3 — Judul" },
      apart3Body: { label: "Kartu 3 — Deskripsi" },
      apart4Title: { label: "Kartu 4 — Judul" },
      apart4Body: { label: "Kartu 4 — Deskripsi" },
      certsEyebrow: { label: "Heading 2 (Sertifikasi & Akreditasi)" },
      certsHeading: { label: "Span Label (Sertifikasi & Akreditasi)" },
      certsBody: { label: "Deskripsi (Sertifikasi & Akreditasi)" },
      cert1Name: { label: "Sertifikasi 1 — Nama" },
      cert1Detail: { label: "Sertifikasi 1 — Detail" },
      cert2Name: { label: "Sertifikasi 2 — Nama" },
      cert2Detail: { label: "Sertifikasi 2 — Detail" },
      cert3Name: { label: "Sertifikasi 3 — Nama" },
      cert3Detail: { label: "Sertifikasi 3 — Detail" },
      cert4Name: { label: "Sertifikasi 4 — Nama" },
      cert4Detail: { label: "Sertifikasi 4 — Detail" },
      ctaTitle: { label: "Heading 2 (CTA)" },
      ctaBody: { label: "Deskripsi (CTA)" },
      ctaButton: { label: "Tombol (CTA)" },
    },
  },
  SolutionsPage: {
    order: [
      "metaTitle",
      "metaDescription",
      "headerEyebrow",
      "headerTitle",
      "headerDescription",
      "pillar1Tagnum",
      "pillar1Eyebrow",
      "pillar1Title",
      "pillar1Lead",
      "pillar1Cap1Title",
      "pillar1Cap1Body",
      "pillar1Cap2Title",
      "pillar1Cap2Body",
      "pillar1Cap3Title",
      "pillar1Cap3Body",
      "pillar1Cap4Title",
      "pillar1Cap4Body",
      "pillar2Tagnum",
      "pillar2Eyebrow",
      "pillar2Title",
      "pillar2Lead",
      "pillar2GroupAirTitle",
      "pillar2Cap1Title",
      "pillar2Cap1Body",
      "pillar2Cap2Title",
      "pillar2Cap2Body",
      "pillar2Cap3Title",
      "pillar2Cap3Body",
      "pillar2GroupLiquidTitle",
      "pillar2Cap4Title",
      "pillar2Cap4Body",
      "pillar2Cap5Title",
      "pillar2Cap5Body",
      "pillar2Cap6Title",
      "pillar2Cap6Body",
      "pillar2Cap7Title",
      "pillar2Cap7Body",
      "pillar2CatalogCta",
      "pillar3Tagnum",
      "pillar3Eyebrow",
      "pillar3Title",
      "pillar3Lead",
      "pillar3Cap1Title",
      "pillar3Cap1Body",
      "pillar3Cap2Title",
      "pillar3Cap2Body",
      "pillar3Cap3Title",
      "pillar3Cap3Body",
      "aftersalesTitle",
      "aftersalesBody",
      "aftersalesPoint1Bold",
      "aftersalesPoint1Rest",
      "aftersalesPoint2Bold",
      "aftersalesPoint2Rest",
      "aftersalesPoint3Bold",
      "aftersalesPoint3Rest",
      "aftersalesPoint4Bold",
      "aftersalesPoint4Rest",
      "aftersalesPoint5Bold",
      "aftersalesPoint5Rest",
      "aftersalesPoint6Bold",
      "aftersalesPoint6Rest",
      "yuchaiEyebrow",
      "yuchaiHeading",
      "yuchaiBody",
      "yuchaiCta",
      "integratedEyebrow",
      "integratedHeading",
      "integratedBody",
      "brandsEyebrow",
      "brandsHeading",
      "brandsBody",
      "ctaTitle",
      "ctaBody",
      "ctaButton",
    ],
    fields: {
      metaTitle: { label: "Meta Title" },
      metaDescription: { label: "Meta Description" },
      headerEyebrow: { label: "Heading 1" },
      headerTitle: { label: "Span Label" },
      headerDescription: { label: "Deskripsi Header" },
      pillar1Tagnum: { label: "Pilar 1 (Power) — Tag" },
      pillar1Eyebrow: { label: "Heading 2 (Pilar 1 — Power)" },
      pillar1Title: { label: "Span Label (Pilar 1 — Power)" },
      pillar1Lead: { label: "Deskripsi (Pilar 1 — Power)" },
      pillar1Cap1Title: { label: "Pilar 1 — Kapabilitas 1 Judul" },
      pillar1Cap1Body: { label: "Pilar 1 — Kapabilitas 1 Deskripsi" },
      pillar1Cap2Title: { label: "Pilar 1 — Kapabilitas 2 Judul" },
      pillar1Cap2Body: { label: "Pilar 1 — Kapabilitas 2 Deskripsi" },
      pillar1Cap3Title: { label: "Pilar 1 — Kapabilitas 3 Judul" },
      pillar1Cap3Body: { label: "Pilar 1 — Kapabilitas 3 Deskripsi" },
      pillar1Cap4Title: { label: "Pilar 1 — Kapabilitas 4 Judul" },
      pillar1Cap4Body: { label: "Pilar 1 — Kapabilitas 4 Deskripsi" },
      pillar2Tagnum: { label: "Pilar 2 (Cooling) — Tag" },
      pillar2Eyebrow: { label: "Heading 2 (Pilar 2 — Cooling)" },
      pillar2Title: { label: "Span Label (Pilar 2 — Cooling)" },
      pillar2Lead: { label: "Deskripsi (Pilar 2 — Cooling)" },
      pillar2GroupAirTitle: { label: "Pilar 2 — Sub-judul (Air Cooling)" },
      pillar2Cap1Title: { label: "Pilar 2 — Kapabilitas 1 Judul" },
      pillar2Cap1Body: { label: "Pilar 2 — Kapabilitas 1 Deskripsi" },
      pillar2Cap2Title: { label: "Pilar 2 — Kapabilitas 2 Judul" },
      pillar2Cap2Body: { label: "Pilar 2 — Kapabilitas 2 Deskripsi" },
      pillar2Cap3Title: { label: "Pilar 2 — Kapabilitas 3 Judul" },
      pillar2Cap3Body: { label: "Pilar 2 — Kapabilitas 3 Deskripsi" },
      pillar2GroupLiquidTitle: { label: "Pilar 2 — Sub-judul (Liquid Cooling)" },
      pillar2Cap4Title: { label: "Pilar 2 — Kapabilitas 4 Judul" },
      pillar2Cap4Body: { label: "Pilar 2 — Kapabilitas 4 Deskripsi" },
      pillar2Cap5Title: { label: "Pilar 2 — Kapabilitas 5 Judul" },
      pillar2Cap5Body: { label: "Pilar 2 — Kapabilitas 5 Deskripsi" },
      pillar2Cap6Title: { label: "Pilar 2 — Kapabilitas 6 Judul" },
      pillar2Cap6Body: { label: "Pilar 2 — Kapabilitas 6 Deskripsi" },
      pillar2Cap7Title: { label: "Pilar 2 — Kapabilitas 7 Judul" },
      pillar2Cap7Body: { label: "Pilar 2 — Kapabilitas 7 Deskripsi" },
      pillar2CatalogCta: { label: "Tombol (Katalog Midea Data Center)" },
      pillar3Tagnum: { label: "Pilar 3 (Monitoring) — Tag" },
      pillar3Eyebrow: { label: "Heading 2 (Pilar 3 — Monitoring)" },
      pillar3Title: { label: "Span Label (Pilar 3 — Monitoring)" },
      pillar3Lead: { label: "Deskripsi (Pilar 3 — Monitoring)" },
      pillar3Cap1Title: { label: "Pilar 3 — Kapabilitas 1 Judul" },
      pillar3Cap1Body: { label: "Pilar 3 — Kapabilitas 1 Deskripsi" },
      pillar3Cap2Title: { label: "Pilar 3 — Kapabilitas 2 Judul" },
      pillar3Cap2Body: { label: "Pilar 3 — Kapabilitas 2 Deskripsi" },
      pillar3Cap3Title: { label: "Pilar 3 — Kapabilitas 3 Judul" },
      pillar3Cap3Body: { label: "Pilar 3 — Kapabilitas 3 Deskripsi" },
      aftersalesTitle: { label: "Heading 2 (After Sales)" },
      aftersalesBody: { label: "Deskripsi (After Sales)" },
      aftersalesPoint1Bold: { label: "Poin 1 — Teks Tebal" },
      aftersalesPoint1Rest: { label: "Poin 1 — Teks Lanjutan" },
      aftersalesPoint2Bold: { label: "Poin 2 — Teks Tebal" },
      aftersalesPoint2Rest: { label: "Poin 2 — Teks Lanjutan" },
      aftersalesPoint3Bold: { label: "Poin 3 — Teks Tebal" },
      aftersalesPoint3Rest: { label: "Poin 3 — Teks Lanjutan" },
      aftersalesPoint4Bold: { label: "Poin 4 — Teks Tebal" },
      aftersalesPoint4Rest: { label: "Poin 4 — Teks Lanjutan" },
      aftersalesPoint5Bold: { label: "Poin 5 — Teks Tebal" },
      aftersalesPoint5Rest: { label: "Poin 5 — Teks Lanjutan" },
      aftersalesPoint6Bold: { label: "Poin 6 — Teks Tebal" },
      aftersalesPoint6Rest: { label: "Poin 6 — Teks Lanjutan" },
      yuchaiEyebrow: { label: "Heading 2 (Video Yuchai)" },
      yuchaiHeading: { label: "Span Label (Video Yuchai)" },
      yuchaiBody: { label: "Deskripsi (Video Yuchai)" },
      yuchaiCta: { label: "Tombol (Video Yuchai)" },
      integratedEyebrow: { label: "Heading 2 (Integrated)" },
      integratedHeading: { label: "Span Label (Integrated)" },
      integratedBody: { label: "Deskripsi (Integrated)", kind: "rich" },
      brandsEyebrow: { label: "Heading 2 (Brand)" },
      brandsHeading: { label: "Span Label (Brand)" },
      brandsBody: { label: "Deskripsi (Brand)" },
      ctaTitle: { label: "Heading 2 (CTA)" },
      ctaBody: { label: "Deskripsi (CTA)" },
      ctaButton: { label: "Tombol (CTA)" },
    },
  },
  DataCenterPage: {
    order: [
      "metaTitle",
      "metaDescription",
      "heroTitle",
      "heroBody",
      "heroCtaPrimary",
      "heroCtaSecondary",
      "liquidEyebrow",
      "liquidHeading",
      "liquidIntro",
      "liquidCard1Title",
      "liquidCard1Spec",
      "liquidCard1Body",
      "liquidCard2Title",
      "liquidCard2Spec",
      "liquidCard2Body",
      "liquidCard3Title",
      "liquidCard3Spec",
      "liquidCard3Body",
      "liquidCard4Title",
      "liquidCard4Spec",
      "liquidCard4Body",
      "liquidCta",
      "mappingEyebrow",
      "mappingHeading",
      "mappingBody",
      "mappingThNeed",
      "mappingThCapability",
      "whyEyebrow",
      "whyHeading",
      "scopeEyebrow",
      "scopeHeading",
      "scopeBody",
      "scopeViewCapability",
      "ctaTitle",
      "ctaBody",
      "ctaPrimary",
      "ctaSecondary",
    ],
    fields: {
      metaTitle: { label: "Meta Title" },
      metaDescription: { label: "Meta Description" },
      heroTitle: { label: "Heading 1 (Hero)" },
      heroBody: { label: "Deskripsi (Hero)" },
      heroCtaPrimary: { label: "Tombol Utama (Hero)" },
      heroCtaSecondary: { label: "Tombol Sekunder (Hero)" },
      liquidEyebrow: { label: "Heading 2 (Liquid Cooling)" },
      liquidHeading: { label: "Span Label (Liquid Cooling)" },
      liquidIntro: { label: "Deskripsi (Liquid Cooling)" },
      liquidCard1Title: { label: "Kartu 1 — Judul (Maglev Active CDU)" },
      liquidCard1Spec: { label: "Kartu 1 — Spek" },
      liquidCard1Body: { label: "Kartu 1 — Deskripsi" },
      liquidCard2Title: { label: "Kartu 2 — Judul (Industrial-Grade CDU)" },
      liquidCard2Spec: { label: "Kartu 2 — Spek" },
      liquidCard2Body: { label: "Kartu 2 — Deskripsi" },
      liquidCard3Title: { label: "Kartu 3 — Judul (Liquid-Cooling Terminals)" },
      liquidCard3Spec: { label: "Kartu 3 — Spek" },
      liquidCard3Body: { label: "Kartu 3 — Deskripsi" },
      liquidCard4Title: { label: "Kartu 4 — Judul (Air-Fluid Synergy)" },
      liquidCard4Spec: { label: "Kartu 4 — Spek" },
      liquidCard4Body: { label: "Kartu 4 — Deskripsi" },
      liquidCta: { label: "Tombol (Lihat Katalog)" },
      mappingEyebrow: { label: "Heading 2 (Pemetaan Kapabilitas)" },
      mappingHeading: { label: "Span Label (Pemetaan Kapabilitas)" },
      mappingBody: { label: "Deskripsi (Pemetaan Kapabilitas)" },
      mappingThNeed: { label: "Tabel — Kolom Kebutuhan" },
      mappingThCapability: { label: "Tabel — Kolom Kapabilitas" },
      whyEyebrow: { label: "Heading 2 (Mengapa Penting)" },
      whyHeading: { label: "Span Label (Mengapa Penting)" },
      scopeEyebrow: { label: "Heading 2 (Lingkup Infrastruktur)" },
      scopeHeading: { label: "Span Label (Lingkup Infrastruktur)" },
      scopeBody: { label: "Deskripsi (Lingkup Infrastruktur)" },
      scopeViewCapability: { label: "Tombol (Lihat Kapabilitas)" },
      ctaTitle: { label: "Heading 2 (CTA)" },
      ctaBody: { label: "Deskripsi (CTA)" },
      ctaPrimary: { label: "Tombol Utama (CTA)" },
      ctaSecondary: { label: "Tombol Sekunder (CTA)" },
    },
  },
  MideaDataCenterPage: {
    order: [
      "metaTitle",
      "metaDescription",
      "heroEyebrow",
      "heroTitle",
      "heroBody",
      "overviewEyebrow",
      "overviewHeading",
      "overviewBody",
      "overviewImage",
      "overviewImageAlt",
      "catalogEyebrow",
      "catalogHeading",
      "catalogBody",
      "catalogImage",
      "catalogImageAlt",
      "catalogCaption",
      "productsEyebrow",
      "productsHeading",
      "productsBody",
      "card1Title",
      "card1Body",
      "card2Title",
      "card2Body",
      "card3Title",
      "card3Body",
      "card4Title",
      "card4Body",
      "ctaTitle",
      "ctaBody",
      "ctaButton",
      "backToSolutions",
      "backToDataCenter",
    ],
    fields: {
      metaTitle: { label: "Meta Title" },
      metaDescription: { label: "Meta Description" },
      heroEyebrow: { label: "Heading 1 (Eyebrow Hero)" },
      heroTitle: { label: "Span Label (Hero)" },
      heroBody: { label: "Deskripsi (Hero)" },
      overviewEyebrow: { label: "Heading 2 (Overview)" },
      overviewHeading: { label: "Span Label (Overview)" },
      overviewBody: { label: "Deskripsi (Overview)" },
      overviewImage: { label: "URL Gambar (Arsitektur)" },
      overviewImageAlt: { label: "Teks Alt Gambar (Arsitektur)" },
      catalogEyebrow: { label: "Heading 2 (Katalog)" },
      catalogHeading: { label: "Span Label (Katalog)" },
      catalogBody: { label: "Deskripsi (Katalog)" },
      catalogImage: { label: "URL Gambar Katalog" },
      catalogImageAlt: { label: "Teks Alt Gambar Katalog" },
      catalogCaption: { label: "Keterangan Gambar" },
      productsEyebrow: { label: "Heading 2 (Produk)" },
      productsHeading: { label: "Span Label (Produk)" },
      productsBody: { label: "Deskripsi (Produk)" },
      card1Title: { label: "Produk 1 — Judul" },
      card1Body: { label: "Produk 1 — Deskripsi" },
      card2Title: { label: "Produk 2 — Judul" },
      card2Body: { label: "Produk 2 — Deskripsi" },
      card3Title: { label: "Produk 3 — Judul" },
      card3Body: { label: "Produk 3 — Deskripsi" },
      card4Title: { label: "Produk 4 — Judul" },
      card4Body: { label: "Produk 4 — Deskripsi" },
      ctaTitle: { label: "Heading 2 (CTA)" },
      ctaBody: { label: "Deskripsi (CTA)" },
      ctaButton: { label: "Tombol (CTA)" },
      backToSolutions: { label: "Tautan — Kembali ke Solusi" },
      backToDataCenter: { label: "Tautan — Kembali ke Data Center" },
    },
  },
};
